name = "company-contact-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 開発環境用の設定をここに残しても良い
# [vars]
# ALLOWED_ORIGINS = "http://localhost:3000"
# RECIPIENT_EMAIL = "dev@example.com"

[env.production]
# 本番用の変数をこちらに定義します
[env.production.vars]
ALLOWED_ORIGINS = "https://global-genex.com,https://www.global-genex.com"
RECIPIENT_EMAIL = "info@mail.global-genex.com"

[env.staging]
[env.development]

[build]
command = "npm run build"